name: Build and Push Docker Image (with dynamic tag)

on:
  push:
    branches:
      - development

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        run: echo "dckr_pat_a0t8MKXraVg4zXwfTIYqaaOeyu8" | docker login -u saurabh2025operatiomarketing --password-stdin

      - name: Set Dynamic Image Tag
        id: vars
        run: echo "TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Build and Push Docker Image with Timestamp Tag
        run: |
          docker build -t saurabh2025operatiomarketing/rocket-advance-investor:${TAG} .
          docker push saurabh2025operatiomarketing/rocket-advance-investor:${TAG}
